services:
  stats:
    image: stats:latest
    build: stats
    restart: "no"
    ports:
      - "9090:9090"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9090/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - DB_HOST=stats-db
      - DB_PORT=5432
      - DB_NAME=ewm
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    depends_on:
      - stats-db

  stats-db:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: ewm
    ports:
      - "8080:8080"
    container_name: ewm-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - DB_NAME=ewm
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    depends_on:
      - ewm-db


  ewm-db:
    image: postgres:16.1
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=ewm
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
