server:
  port: 9090

spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: embedded
  datasource:
    url: jdbc:h2:file:./data/stats
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true