server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev
  cloud:
    openfeign:
      okhttp:
        enabled: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: embedded
  datasource:
    url: jdbc:h2:file:./data/ewm
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true