server:
  port: 8080

spring:
  sql:
    init:
      mode: always
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

stats-server:
  url: ${STATS_SERVICE_URL:http://localhost:9090}
  hit: "/hit"
  stats: "/stats"