server:
  port: 8080

spring:
  cloud:
    openfeign:
      okhttp:
        enabled: true
  sql:
    init:
      mode: embedded
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

stats:
  url: ${host:http://localhost:9090}